# Generated by Django 4.0.1 on 2022-11-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carules/')),
            ],
        ),
        migrations.CreateModel(
            name='Carusel_02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carusel/')),
            ],
        ),
        migrations.CreateModel(
            name='Carusel_03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carules/')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageMon_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monuments/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageMon_02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monuments/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageMon_03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monuments/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageMon_04',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monuments/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageMon_05',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monuments/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageMon_06',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monuments/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='latest_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('news', models.CharField(max_length=300)),
            ],
        ),
    ]
