# Generated by Django 4.0.1 on 2022-11-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monuments/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(choices=[(1, 'item 1'), (2, 'item 2'), (3, 'item 3'), (4, 'item 4'), (5, 'item 5'), (6, 'item 6')], default='1', max_length=10)),
            ],
        ),
    ]
