# Generated by Django 4.0.1 on 2022-11-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0003_rename_description_homepagegallery_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagegallery',
            name='item',
            field=models.CharField(choices=[('1', 'gallery 1'), ('2', 'gallery 2'), ('3', 'gallery 3'), ('4', 'gallery 4'), ('5', 'gallery 5'), ('6', 'gallery 6'), ('7', 'gallery 7'), ('8', 'gallery 8')], default='1', max_length=10),
        ),
    ]
