# Generated by Django 4.0.1 on 2022-11-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0004_alter_homepagegallery_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carules/')),
                ('item', models.CharField(choices=[('1', 'carusel 1'), ('2', 'carusel 2'), ('3', 'carusel 3')], default='1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monuments/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(choices=[('1', 'Monument 1'), ('2', 'Monument 2'), ('3', 'Monument 3'), ('4', 'Monument 4'), ('5', 'Monument 5'), ('6', 'Monument 6')], default='1', max_length=10)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Carusel_01',
        ),
        migrations.DeleteModel(
            name='Carusel_02',
        ),
        migrations.DeleteModel(
            name='Carusel_03',
        ),
        migrations.DeleteModel(
            name='HomePageMon_01',
        ),
        migrations.DeleteModel(
            name='HomePageMon_02',
        ),
        migrations.DeleteModel(
            name='HomePageMon_03',
        ),
        migrations.DeleteModel(
            name='HomePageMon_04',
        ),
        migrations.DeleteModel(
            name='HomePageMon_05',
        ),
        migrations.DeleteModel(
            name='HomePageMon_06',
        ),
    ]
