# Generated by Django 4.0.1 on 2022-11-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0005_carusel_homepagemon_delete_carusel_01_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monuments/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
