# Generated by Django 4.0.1 on 2022-11-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0006_homepagetop'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='monuments/')),
                ('url', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(choices=[('1', 'video 1'), ('2', 'video 2'), ('3', 'video 3'), ('4', 'video 4')], default='1', max_length=10)),
            ],
        ),
    ]
