# Generated by Django 4.0.1 on 2022-11-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0007_homepagevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagevideo',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagevideo',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
