# Generated by Django 4.0.1 on 2022-11-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0008_alter_homepagevideo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
    ]
