# Generated by Django 4.0.1 on 2022-11-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0010_alter_carusel_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=300)),
                ('destrict', models.CharField(choices=[('1', 'Mary'), ('2', 'Lebap'), ('3', 'Ahal'), ('4', 'Balkan'), ('5', 'Dashoguz')], default='1', max_length=100)),
                ('category', models.CharField(choices=[('1', 'Monument'), ('2', 'Reserve'), ('3', 'Nature')], default=1, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
            ],
        ),
    ]
