# Generated by Django 4.0.1 on 2022-11-18 04:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0011_allpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpost',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
