# Generated by Django 4.0.1 on 2022-11-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0012_alter_allpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpost',
            name='destrict',
            field=models.CharField(choices=[('mary', 'Mary'), ('lebap', 'Lebap'), ('ahal', 'Ahal'), ('balkan', 'Balkan'), ('dasoguz', 'Dashoguz')], default='1', max_length=100),
        ),
    ]
