# Generated by Django 4.0.1 on 2022-11-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0016_alter_allpost_category_alter_allpost_destrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='url',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
