# Generated by Django 4.0.1 on 2022-11-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0017_allpost_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpost',
            name='url',
        ),
    ]
