# Generated by Django 4.0.1 on 2023-01-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0018_remove_allpost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpost',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tm', 'Türkmen')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='carusel',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tm', 'Türkmen')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='gallerypagegallery',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tm', 'Türkmen')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='homepagegallery',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tm', 'Türkmen')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='homepagemon',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tm', 'Türkmen')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='homepagevideo',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tm', 'Türkmen')], default='en', max_length=5),
        ),
    ]
