# Generated by Django 4.0.1 on 2023-01-24 13:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0019_allpost_language_carusel_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpost',
            name='language',
        ),
        migrations.RemoveField(
            model_name='carusel',
            name='language',
        ),
        migrations.RemoveField(
            model_name='gallerypagegallery',
            name='language',
        ),
        migrations.RemoveField(
            model_name='homepagegallery',
            name='language',
        ),
        migrations.RemoveField(
            model_name='homepagemon',
            name='language',
        ),
        migrations.RemoveField(
            model_name='homepagevideo',
            name='language',
        ),
        migrations.AddField(
            model_name='allpost',
            name='content_in_turkmen',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='allpost',
            name='description_in_turkmen',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='allpost',
            name='title_in_turkmen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carusel',
            name='description_in_turkmen',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carusel',
            name='title_in_turkmen',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallerypagegallery',
            name='description_in_turkmen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gallerypagegallery',
            name='name_in_turkmen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagegallery',
            name='name_in_turkmen',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='homepagemon',
            name='description_in_turkmen',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='homepagemon',
            name='title_in_turkmen',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='homepagetop',
            name='description_in_turkmen',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='homepagetop',
            name='title_in_turkmen',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='homepagevideo',
            name='description_in_turkmen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagevideo',
            name='title_in_turkmen',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='latest_news',
            name='category_in_turkmen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='latest_news',
            name='news_in_turkmen',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
